const quotes = [
    "Believe you can and you're halfway there.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Diamonds are created under pressure.",
    "If you want to buy something without looking at the price tag, you have to work without looking at the clock.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Hard work beats talent when talent doesn't work hard.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The way to get started is to quit talking and begin doing.",
    "Don't watch the clock; do what it does. Keep going.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Opportunities don't happen. You create them.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "You are never too old to set another goal or to dream a new dream.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The only way to do great work is to love what you do.",
    "The best way to predict the future is to create it.",
    "Yesterday is the past, tomorrow is the future, that's why today is the present",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "The only place where success comes before work is in the dictionary.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Opportunities are usually disguised as hard work, so most people don't recognize them.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Do not wait to strike till the iron is hot, but make it hot by striking.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The way to get started is to quit talking and begin doing.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Don’t watch the clock; do what it does. Keep going.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "In the middle of every difficulty lies opportunity.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",
    "Life is either a daring adventure or nothing at all.",
    "The best revenge is massive success.",
    "Start where you are. Use what you have. Do what you can.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Act as if what you do makes a difference. It does.",
    "The only way to do great work is to love what you do.",
    "The journey of a thousand miles begins with one step.",
    "Everything you can imagine is real.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your time is limited, don’t waste it living someone else’s life.",
    "If you want to achieve greatness stop asking for permission.",
    "The only person you are destined to become is the person you decide to be.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart."
];
