const quotes = [
    "Believe you can and you're halfway there.",
    "Your limitation—it’s only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Diamonds are created under pressure.",
    "If you want to buy something without looking at the price tag, you have to work without looking at the clock.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "Hard work beats talent when talent doesn't work hard.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The way to get started is to quit talking and begin doing.",
    "Don't watch the clock; do what it does. Keep going.",
    "Keep your face always toward the sunshine—and shadows will fall behind you.",
    "Opportunities don't happen. You create them.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Everything you’ve ever wanted is on the other side of fear.",
    "You are never too old to set another goal or to dream a new dream.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The only way to do great work is to love what you do.",
    "The best way to predict the future is to create it.",
    "Yesterday is the past, tomorrow is the future, that's why today is the present",
];
